### ISSUE TITLE
针对公式复制行的时候,增加公式复制,我把xjava去掉了太多,我拷贝我针对公式这块的,代码比较简陋

### ISSUE THREAD

**Issue by bandhzh** [HY-Org/hy.common.report#4]
else if ( v_CellType == CellType.FORMULA) 
        {
            i_DataCell.setCellType(v_CellType);
            String cellFormula = i_TemplateCell.getCellFormula();
            Integer direction = i_RTemplate.getDirection();
            Matcher m = cellFormula_Pattern.matcher(cellFormula);
            int nextBegin = 0;
            if(direction == RTemplate.$Direction_Vertical){// 横向
            	while(m.find()){
            		String group = m.group();
            		Matcher matcher = cellFormula_num_Pattern.matcher(group);
            		matcher.find();
            		String group2 = matcher.group();
            		int newData = Integer.parseInt(group2) + io_RTotal.getRealDataCount() - 1;
            		String replaceAll = group.replaceAll("[0-9]+", String.valueOf(newData));
            		cellFormula = cellFormula.substring(0,m.start() + nextBegin) +  replaceAll + cellFormula.substring(m.end() + nextBegin,cellFormula.length());
            		if(String.valueOf(newData).length() > group2.length()){
            			nextBegin = nextBegin + String.valueOf(newData).length() - group2.length();
            		}
            	}
            }else if(direction == RTemplate.$Direction_Horizontal){
            	while(m.find()){
            		String group = m.group();
            		Matcher matcher = cellFormula_char_Pattern.matcher(group);
            		matcher.find();
            		String group2 = matcher.group();
            		String newGroup = group2;
            		if(group2.length() == 1){
            			char xy = group2.charAt(0);
            			int nextInt = io_RTotal.getRealDataCount() - 1;
            			if((xy + nextInt) > 90){
            				newGroup = "A" + (char)((xy + nextInt - 90) + 64);
            			}else{
            				newGroup = String.valueOf(new char[]{(char)(xy + nextInt)});
            			}
            		}else{
            			char xy1 = group2.charAt(0);
            			char xy = group2.charAt(1);
            			int nextInt = io_RTotal.getRealDataCount() - 1;
            			if((xy + nextInt) > 90){
            				newGroup = "" + (char)(xy1 + 1) + (char)((xy + nextInt - 90) + 64);
            			}else{
            				newGroup = String.valueOf(new char[]{xy1,(char)(xy + nextInt)});
            			}
            		}
            		String replaceAll = group.replaceAll("[A-Za-z]+", newGroup);
            		cellFormula = cellFormula.substring(0,m.start() + nextBegin) +  replaceAll + cellFormula.substring(m.end() + nextBegin,cellFormula.length());
            		if(newGroup.length() > group2.length()){
            			nextBegin = nextBegin + newGroup.length() - group2.length();
            		}
            	}
            }
            i_DataCell.setCellFormula(cellFormula);//
        }

**Comment by HY-ZhengWei** [comment]
好的，后面融合一下哈，谢谢

**Comment by HY-ZhengWei** [comment]
感谢，现已融合。
